### ISSUE TITLE
Does not work with images

### ISSUE THREAD

**Issue by rushzx** [Will-Renius/TextFormulaConverter#1]
Try it:
=image("http://www.imc-companies.com/taegutec/ttkCatalogFiles/datafile/PICTURE/571.gif";1)
would be great, if you modern it

**Comment by Will-Renius** [comment]
Thanks for letting me know. I'll look into it

**Comment by Will-Renius** [comment]
Uploaded fix to the appstore, should be working now

**Comment by rushzx** [comment]
Wow, so cool! Thanks for answering))
