### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by garfolino** [Will-Renius/TextFormulaConverter#2]
![brubar_-_bpo_to_mfd_-_google_sheets](https://user-images.githubusercontent.com/14035979/39323038-ed17c4d8-4961-11e8-92af-07892f82e852.png)

![brubar_-_bpo_to_mfd_-_google_sheets](https://user-images.githubusercontent.com/14035979/39323076-046d1ea8-4962-11e8-8bfd-0fd8b2438c3b.png)

**Comment by Will-Renius** [comment]
Thanks for the notice, I'll look into it

**Comment by Will-Renius** [comment]
Looks to be an issue with the new verification process. For now you have to uninstall and re-install while telling google it's okay to run the unverified application.
